### ISSUE TITLE
Compatibility of the CLI with `opam-installer`

### ISSUE THREAD

**Issue by vbgl** [jaapb/opaline#1]
I’m trying to use `opaline` as a drop-in replacement for `opam-installer`. It would be very convenient if the two tools had a common command-line interface. Here are some annoying differences.

Binary name: one is called `opam-installer`, the other one `opaline`.

One-dash-space vs. two-dashes-equal, as in `-libdir /path/to/lib` vs. `--libdir=/path/to/lib`.

Optional argument `-i`/`--install`: this is the default for `opam-installer` but makes `opaline` abort.

Default name: with `opaline` the package name should be given; with `opam-installer` it defaults to the “basename of the .install file”.

If no `.install` file is given, `opam-installer` looks for them in the current directory; `opaline` aborts.

**Comment by jaapb** [comment]
Good point. Shouldn't be too difficult to sort out, I'll have a stab at it when I have a bit of free time.
