### ISSUE TITLE
Several opam files in same folder

### ISSUE THREAD

**Issue by Pitometsu** [jaapb/opaline#3]
Hello. I have project with two opam files at root. E. g. `project.opam` and `development.opam` (for dev toolchain dependencies).

So I build it like:
```
dune build -p $pname
```
And trying to install:
```
opaline -name $pname -prefix $out -libdir $OCAMLFIND_DESTDIR
```

But got an error:
```
Fatal error: exception Opaline.File_nonexistent("_build/install/default/lib/development/META")
```
Is it an expected behaviour? How to install only some packages?

**Comment by Pitometsu** [comment]
Oh, looks like I missed an extra `development.install` file. Sorry for disturb.

**Comment by jaapb** [comment]
Hey, I'm happy that a) people use this and b) bugs appear to solve themselves :) Cheers!
