### ISSUE TITLE
Still needed vs `opam-installer` package?

### ISSUE THREAD

**Issue by timbertson** [jaapb/opaline#4]
Hello, this is more of a question than an issue. I maintain `opam2nix`, which has a need for installing `.install` files without relying on opam itself. I helped split out the `opam-installer` package from the rest of `opam` for this purpose: https://github.com/ocaml/opam/pull/3061. I only found out about this project today, since I noticed it used in nix's `buildDunePackage` functionality.

I don't know the history of this project, it may be we were just unaware of each other's efforts? As I see it, the main differences from just using `opam-installer` are:
 - `opam-installer` has a couple more dependencies - cmdliner and dune. You mention "lightweight" in your readme, but I can't tell if you mean these dependencies or just want something that doesn't bring the full weight of `opam` with it (which used to be the only way to get the `opam-installer` binary).
 - `opam-installer` should always be 1:1 with the rest of the ecosystem, since it's part of opam proper. Eliminates issues like #2 and any other bugs where this differs from "real" opam.

So, I mostly wanted to point out the duplication and wonder whether there's still a need for this over the standalone `opam-installer` package. If so, it might be good to point this out in the readme since it's unclear whether you're comparing this to `opam-installer` or full `opam`.

(/cc @vbgl for visibility in nixpkgs)

**Comment by jaapb** [comment]
The original point of opaline was that `opam` had a problem with circular dependencies; if I recall correctly, `dune` needed `opam-installer`, but `opam` needed `dune`. So "lightweight" refers to that (though the fact that you didn't need the whole weight of opam certainly was a nice bonus).

If that particular problem is now solved (and I seem to recall a message on the caml list where this was confirmed - if I recall correctly `dune` can now be built and installed without `opam`) then indeed opaline is not strictly necessary anymore. I'm still keeping it around though; it's used in `pkgsrc`, for one, where it seems to do the job nicely (and the fact that it doesn't have any dependencies can be a bonus - we have several packages that use `opam` but not `dune`). I will have a look at the README file and clarify the issue, though.

**Comment by timbertson** [comment]
Good to know, thanks. Yeah I believe the circular issue has been fixed, I think `dune` effectively copied / reimplemented the install code to break the dependency on opam.
